
PROGS= fim1 fim2 fim3 fim4

CC=gcc -Wall


all: $(PROGS)

clean:
	rm -f $(PROGS)

fim1:	fim1.c
	$(CC) fim1.c -o fim1

fim2:	fim2.c
	$(CC) fim2.c -o fim2

fim3:	fim3.c
	$(CC) fim3.c -o fim3

fim4:	fim4.c
	$(CC) fim4.c -o fim4
