
PROGS= id amb arg str

CC=gcc -Wall


all: $(PROGS)

clean:
	rm -f $(PROGS)

id:	id.c
	$(CC) id.c -o id

amb:	amb.c
	$(CC) amb.c -o amb

arg:	arg.c
	$(CC) arg.c -o arg

str:	str.c
	$(CC) str.c -o str
